---

# This will shutup the python vs. python3 deprecation warning.
# 'auto' will be future default per this page:
#
#   https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html
ansible_python_interpreter: 'auto'

# To get the latest version number:
# - https://www.plex.tv/media-server-downloads/
# - Select "linux" in the dropdown
# - Version number will be displayed on page.

# plex_version: '1.18.9.2571-e106a8a91'
plex_version: '1.18.9.2578-513b381af'

media_directory: 'media'
media_group: 'mediausers'

media_static_folders:
  - 'historian_export'
  - 'historian_import'
  - 'source_music'
  - 'source_photos'
  - 'source_photos/lance_photosync'
  - 'source_photos/alison_photosync'
  - 'mobile_photos'
  - 'mobile_photos_alison'
  - 'mobile_photos_lance'
  - 'music'
  - 'movies'
  - 'photos'
  - 'tv'

backup_share: 'backup'
backup_path: '/backup'

filesystems__devices: '{{ snapraid__parity_devices + snapraid__data_devices }}'

mergerfs__mount_point: '/storage'
mergerfs__mount_options: 'defaults,allow_other,direct_io,use_ino,category.create=eplfs,moveonenospc=true,minfreespace=20G,fsname=mergerfsPool'

# Seems like map(...) oughta create a list, but seems to create some sort of
# "generator" object. Would sure be nice if any of the docs were any good.
mergerfs__mounts: '{{ snapraid__data_devices | map(attribute="mount_point") | list }}'

# For mac automounter applescript.
smbd_port: '445'

samba__custom_global:
  'dns proxy'     : 'no'
  'guest ok'      : 'no'
  'hosts allow'   : '10.'
  'security'      : 'user'
  'server role'   : 'standalone server'
  'server string' : 'Samba Server %v'
  'workgroup'     : 'WORKGROUP'

# This syntax is total hackery to allow using a variable as a dictionary key.
# See here:  https://github.com/ansible/ansible/pull/19664
samba__shares: "{
  '{{ media_share }}': {
    'path'           : '{{ mergerfs__mount_point }}',
    'browsable'      : 'yes',
    'create mask'    : '0775',
    'directory mask' : '0775',
    'force group'    : 'mediausers',
    'valid users'    : '@mediausers',
    'writable'       : 'yes',
  },
  '{{ backup_share }}': {
    'path'           : '{{ backup_path }}',
    'browsable'      : 'yes',
    'create mask'    : '0775',
    'directory mask' : '0775',
    'force group'    : 'mediausers',
    'valid users'    : '@mediausers',
    'writable'       : 'yes',
  }
}"

#
# timezone / ntp
#

ntp_enabled: 'true'
ntp_timezone: 'America/Denver'
ntp_manage_config: 'true'

