---

mergerfs_mount_point: '/storage'
mergerfs_mount_options: 'defaults,allow_other,direct_io,use_ino,category.create=eplfs,moveonenospc=true,minfreespace=20G,fsname=mergerfsPool'

media_directory: 'media'
media_group: 'mediausers'
media_users:
    - 'alison'
    - 'ljohnston'

samba__custom_global:
    'dns proxy'     : 'no'
    'guest ok'      : 'no'
    'security'      : 'user'
    'server role'   : 'standalone server'
    'server string' : 'Samba Server %v'
    'workgroup'     : 'WORKGROUP'

samba__shares:
    storage:
        path             : '/storage'
        browsable        : 'yes'
        writable         : 'yes'
        'create mask'    : '0775'
        'directory mask' : '0775'
        'force group'    : 'mediausers'
        'valid users'    : '@mediausers'

