---

# plex_version: '1.15.6.1079-78232c603'
# plex_version: '1.16.1.1246-1d09ac057'
plex_version: '1.16.3.1433-359b06978'

media_directory: 'media'
media_group: 'mediausers'

media_static_folders:
  - 'historian_export'
  - 'historian_import'
  - 'source_music'
  - 'source_photos'
  - 'mobile_photos'
  - 'mobile_photos_alison'
  - 'mobile_photos_lance'
  - 'music'
  - 'movies'
  - 'photos'
  - 'tv'

filesystems__devices: '{{ snapraid__parity_devices + snapraid__data_devices }}'

mergerfs__mount_point: '/storage'
mergerfs__mount_options: 'defaults,allow_other,direct_io,use_ino,category.create=eplfs,moveonenospc=true,minfreespace=20G,fsname=mergerfsPool'

# Seems like map(...) oughta create a list, but seems to create some sort of
# "generator" object. Would sure be nice if any of the docs were any good.
mergerfs__mounts: '{{ snapraid__data_devices | map(attribute="mount_point") | list }}'

samba__custom_global:
  'dns proxy'     : 'no'
  'guest ok'      : 'no'
  'security'      : 'user'
  'server role'   : 'standalone server'
  'server string' : 'Samba Server %v'
  'workgroup'     : 'WORKGROUP'

# This syntax is total hackery to allow using a variable as a dictionary key.
# See here:  https://github.com/ansible/ansible/pull/19664
samba__shares: "{
  '{{ mediaserver_share }}': {
    'path'           : '{{ mergerfs__mount_point }}',
    'browsable'      : 'yes',
    'create mask'    : '0775',
    'directory mask' : '0775',
    'force group'    : 'mediausers',
    'valid users'    : '@mediausers',
    'writable'       : 'yes',
  }
}"

#
# timezone / ntp
#

ntp_enabled: 'true'
ntp_timezone: 'America/Denver'
ntp_manage_config: 'true'

