---
# defaults file for mergerfs

mergerfs__version: '2.28.3'

arch: '{{ (ansible_userspace_bits == "64") | ternary("amd64","i386") }}'

mergerfs__download_file: 'mergerfs_{{ mergerfs__version }}.ubuntu-{{ ansible_distribution_release }}_{{ arch }}.deb'

mergerfs__download_url: 'https://github.com/trapexit/mergerfs/releases/download/{{ mergerfs__version }}/{{ mergerfs__download_file }}'
