---
# ansible-playbook main.yml -i hosts --tags docker_apps -K
# the binary | this.file | -i targets | *optional --tags | -K asks for sudo pass

- hosts: mediaservers
  become: yes

  # Install any galaxy roles here.
  # This doesn't work... ansible "compiles" the playbook and dies if these
  # don't exist.
  # - name: 'install ansible-galaxy roles'
  #   command: 'ansible-galaxy install -r requirements.yml --roles-path roles.galaxy'
  #   delegate_to: localhost
  #   become: no
  #   register: galaxy_roles
  #   changed_when: '"was installed successfully" in galaxy_roles.stdout'

  roles:
    - { role: 'roles.galaxy/geerlingguy.docker', tags: 'docker' }
    - { role: 'roles.galaxy/geerlingguy.ntp',    tags: 'ntp' }
    - { role: 'roles.galaxy/oefenweb.postfix',   tags: 'postfix' }

    - { role: 'filesystems', tags: 'filesystems' }
    - { role: 'snapraid',    tags: 'snapraid' }
    - { role: 'mergerfs',    tags: 'mergerfs' }
    - { role: 'mediaserver', tags: 'mediaserver' }
    - { role: 'samba',       tags: 'samba' }
    - { role: 'restic',      tags: 'restic' }

- hosts: macbook
  connection: local

  roles:
    - { role: 'macbook', tags: 'macbook' }
