---
# ansible-playbook main.yml -i hosts --tags docker_apps -K
# the binary | this.file | -i targets | *optional --tags | -K asks for sudo pass

- hosts: dev,prd
  become: yes

  roles:
    - { role: 'roles.galaxy/geerlingguy.docker', tags: 'docker' }
    - { role: 'roles.galaxy/geerlingguy.ntp',    tags: 'ntp' }
    - { role: 'roles.galaxy/oefenweb.postfix',   tags: 'postfix' }

    - { role: 'snapraid',    tags: 'snapraid' }
    - { role: 'mergerfs',    tags: 'mergerfs' }
    - { role: 'mediaserver', tags: 'mediaserver' }
    - { role: 'samba',       tags: 'samba' }
    - { role: 'restic',      tags: 'restic' }

- hosts: macbook
  connection: local

  roles:
    - { role: 'macbook', tags: 'macbook' }
