---
# - { src: geerlingguy.docker, version: '3.0.0' }
# - { src: geerlingguy.ntp,    version: '2.2.0' }
# - { src: oefenweb.postfix,   version: 'v3.4.0' }
- { src: geerlingguy.docker, version: '4.1.3' }
- { src: geerlingguy.ntp,    version: '2.3.1' }
- { src: oefenweb.postfix,   version: 'v3.6.1' }
