---
# tasks file for samba

- name: 'install samba packages'
  apt:
    pkg: '{{ samba__base_packages }}'
    state: 'present'
    install_recommends: False
  register: samba__register_packages
  until: samba__register_packages is succeeded

- name: 'configure samba'
  template:
    src: 'etc/samba/smb.conf.j2'
    dest: '/etc/samba/smb.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'check samba config' ]

- name: 'start samba services and set to run on boot'
  service: 
    name: '{{ item }}' 
    state: 'started' 
    enabled: true
  with_flattened:
    - '{{ samba__services }}'

- name: 'create samba users'
  shell: >
    (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.name }}
  with_items: "{{ samba__users }}"
  no_log: true
  register: samba__create_users_output
  changed_when: "'Added user' in samba__create_users_output.stdout"
