---

- name: 'create media group'
  group:
    name: '{{ media_group }}'
    state: 'present'

- name: 'create media users'
  user:
    name: '{{ item.name }}'
    create_home: '{{ item.create_home }}'
    password: '{{ item.password | password_hash("sha512") }}'
    shell: '{{ item.shell }}'
    append: 'yes'
    groups: '{{ item.groups + [ media_group ] }}'
    update_password: 'on_create'
  no_log: 'true'
  with_flattened: "{{ media_users }}"


