---
# tasks file for restic

- name: 'install restic'
  import_tasks: 'install.yml'
  tags: ['restic', 'restic_install']

- name: 'init restic repo'
  import_tasks: 'repo.yml'
  tags: ['restic', 'restic_repo']
