---

# 
# Create backup directory with sgid set to ensure all future files will be
# owned by the backup users group.
#
# We'll also set the ACLs on the backup directory to ensure that all future
# files will be group writeable, regardless of what a user's umask may be.
#

- name: 'create backup directory'
  file:
      path: '{{ backup_path }}'
      group: '{{ media_group }}'
      mode: 'ug=rwx,o=rx,g+s'
      state: 'directory'

#
# Set the ACLs on the backup directory...
#

- name: 'set user acl on backup directory'
  acl:
      path: '{{ backup_path }}'
      etype: 'user'
      permissions: 'rwX'
      state: 'present'

- name: 'set group acl on backup directory'
  acl:
      path: '{{ backup_path }}'
      etype: 'group'
      permissions: 'rwX'
      state: 'present'

- name: 'set other acl on backup directory'
  acl:
      path: '{{ backup_path }}'
      etype: 'other'
      permissions: 'rX'
      state: 'present'

#
# ... and set the default ACLs so future files are correct.
#

- name: 'set default user acl on backup directory'
  acl:
      path: '{{ backup_path }}'
      default: true
      etype: 'user'
      permissions: 'rwX'
      state: 'present'

- name: 'set default group acl on backup directory'
  acl:
      path: '{{ backup_path }}'
      default: true
      etype: 'group'
      permissions: 'rwX'
      state: 'present'

- name: 'set default other acl on backup directory'
  acl:
      path: '{{ backup_path }}'
      etype: 'other'
      permissions: 'rX'
      state: 'present'
