---

- name: 'create docker-compose.yml'
  template:
    src: 'docker-compose.yml.j2'
    dest: '/docker-compose.yml'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 
    - 'docker-compose up'

