---

- name: 'copy wait-for-it.sh'
  copy:
    src: 'wait-for-it.sh'
    dest: '/usr/local/bin/'
    mode: '0755'

- name: 'create docker-compose.yml'
  template:
    src: 'docker-compose.yml.j2'
    dest: '/docker-compose.yml'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: 
    - 'docker-compose up'

