---

- name: 'partition drives'
  parted:
      device: "{{ item.device }}"
      number: 1
      label: gpt
      state: present
  loop: "{{ parity_devices + data_devices | flatten(levels=1) }}"

- name: 'create filesystems'
  filesystem:
      dev: "{{ item.device }}1"
      fstype: "{{ item.fs_type }}"
      opts:  "{{ item.fs_opts  }}"
  loop: "{{ parity_devices + data_devices | flatten(levels=1) }}"
  register: create_filesystems

# Re-read facts to get new partition data (need later for mounts)
- name: 're-read facts'
  setup:
      filter: 'ansible_devices'
  when: create_filesystems.changed
