---

- name: 'create filesystems'
  include: 'filesystems.yml'
  tags: ['filesystems']

- name: 'mount drives'
  include: 'mounts.yml'
  tags: ['mounts']

- name: 'configure snapraid'
  include: 'configure_snapraid.yml'
  tags: ['configure', 'snapraid']
