---
# tasks file for mediaserver

- block:
  - name: 'general system config'
    include_tasks: 'config.yml'
  tags: ['config']

- block:
  - name: 'create mounts'
    include_tasks: 'mounts.yml'
  tags: ['mounts']

- block:
  - name: 'create users/groups'
    include_tasks: 'users.yml'
  tags: ['users']

- block:
  - name: 'test'
    include_tasks: 'test.yml'
  tags: ['test']
  when: env == 'dev'

- block:
  - name: 'create files/dirs'
    include_tasks: 'files.yml'
  tags: ['files']

- block:
  - name: 'create data share dirs'
    include_tasks: 'data_shares.yml'
  tags: ['data_shares']

- block:
  - name: 'setup mysql'
    include_tasks: 'mysql.yml'
  tags: ['mysql']

- block:
  - name: 'docker apps'
    include_tasks: 'docker_apps.yml'
  tags: ['docker_apps']

- block:
  - name: 'install ffmpeg'
    include_tasks: 'ffmpeg.yml'
  tags: ['ffmpeg']

- block:
  - name: 'install python packages'
    include_tasks: 'python_packages.yml'
  tags: ['scripts','test']

- block:
  - name: 'install scripts'
    include_tasks: 'scripts.yml'
  tags: ['scripts','test']
