---
# tasks file for mediaserver

- name: 'general system config'
  include_tasks: 'config.yml'
  tags: ['config']

- name: 'create mounts'
  include_tasks: 'mounts.yml'
  tags: ['mounts']


#
# The user tasks set facts are needed in other tasks. Using the
# 'always' tag will ensure they run no matter what tags are passed,
# so the facts will always be available.
#
# TODO: Re-evaluate how to manage dependencies across playbook/tasks?
#

- name: 'create users/groups'
  import_tasks: 'users.yml'
  tags: ['always']

- name: 'create files/dirs'
  include_tasks: 'files.yml'
  tags: ['files']

- name: 'create data share dirs'
  include_tasks: 'data_shares.yml'
  tags: ['data_shares']

- name: 'setup mysql'
  include_tasks: 'mysql.yml'
  tags: ['mysql']

- name: 'docker apps'
  include_tasks: 'docker_apps.yml'
  tags: ['docker_apps']

- name: 'install ffmpeg'
  include_tasks: 'ffmpeg.yml'
  tags: ['ffmpeg']

- name: 'install scripts'
  include_tasks: 'scripts.yml'
  tags: ['scripts','test']

# 'import_tasks' will push the 'when' condition down to imported tasks.
- name: 'test'
  import_tasks: 'test.yml'
  tags: ['test']
  when: env == 'dev'

