---
# tasks file for mediaserver

- name: 'general system config'
  import_tasks: 'config.yml'
  tags: ['mediaserver', 'mediaserver_config']

# - name: 'create mounts'
#   import_tasks: 'mounts.yml'
#   tags: ['mediaserver', 'mediaserver_mounts']

- name: 'create filesystems, mounts'
  import_tasks: 'disks.yml'
  tags: ['mediaserver', 'mediaserver_disks']

#
# NOTE: users.yml sets some facts that other tasks rely on. Each
#       dependent task's tag(s) need to added here to ensure the
#       facts are set when referenced.
#

- name: 'create users/groups'
  import_tasks: 'users.yml'
  tags: ['mediaserver',
         'mediaserver_users',
         'mediaserver_docker_apps',
         'mediaserver_test',
         'restic']

- name: 'create files/dirs'
  import_tasks: 'files.yml'
  tags: ['mediaserver', 'mediaserver_files']

- name: 'create data share dirs'
  import_tasks: 'data_shares.yml'
  tags: ['mediaserver', 'mediaserver_data_shares']

- name: 'setup mysql'
  import_tasks: 'mysql.yml'
  tags: ['mediaserver', 'mediaserver_mysql']

- name: 'docker apps'
  import_tasks: 'docker_apps.yml'
  tags: ['mediaserver', 'mediaserver_docker_apps']

- name: 'install ffmpeg'
  import_tasks: 'ffmpeg.yml'
  tags: ['mediaserver', 'mediaserver_ffmpeg']

- name: 'install scripts'
  import_tasks: 'scripts.yml'
  tags: ['mediaserver', 'mediaserver_scripts']

- name: 'test'
  import_tasks: 'test.yml'
  tags: ['mediaserver', 'mediaserver_test']
  when: env == 'dev'
