---
# tasks file for mediaserver

- name: 'general system config'
  include: 'config.yml'
  tags: ['config']

- name: 'create users/groups'
  include: 'users.yml'
  tags: ['users']

- name: 'create files/dirs'
  include: 'files.yml'
  tags: ['files']

- name: 'create backup dir'
  include: 'backup.yml'
  tags: ['backup']

- name: 'docker apps'
  include: 'docker_apps.yml'
  tags: ['docker_apps']

- name: 'ffmpeg'
  include: 'ffmpeg.yml'
  tags: ['ffmpeg']

- name: 'scripts'
  include: 'scripts.yml'
  tags: ['scripts','test']

- name: 'test'
  include: 'test.yml'
  tags: ['test']
  when: env == 'dev'
