---

- name: 'create users/groups'
  include: 'users.yml'
  tags: ['users']

- name: 'create files/dirs'
  include: 'files.yml'
  tags: ['files']

- name: 'configure samba'
  include: 'samba.yml'
  tags: 'configure_samba'
