---
# tasks file for mediaserver

- name: 'create users/groups'
  include: 'users.yml'
  tags: ['users']

- name: 'create files/dirs'
  include: 'files.yml'
  tags: ['files']

- name: 'docker apps'
  include: 'docker_apps.yml'
  tags: ['docker_apps']

- name: 'scripts'
  include: 'scripts.yml'
  tags: ['scripts']
