---

- name: 'create mergerfs mount point'
  file:
      path: "{{ mergerfs_mount_point }}"
      state: directory

- name: 'create mergerfs mount'
  mount:
      path: "{{ mergerfs_mount_point }}"
      src: "{{ data_devices | map(attribute='mount_point') | list | join(':') }}"
      fstype: "fuse.mergerfs"
      opts: "{{ mergerfs_mount_options }}"
      state: mounted
  loop: "{{ parity_devices + data_devices | flatten(levels=1) }}"
    
# - debug:
#     msg: "{{ data_devices | map(attribute='mount_point') | list | join(':') }} {{ mergerfs_mount_point }} fuse.mergerfs {{ mergerfs_mount_options }} 0 0"
