---
# tasks file for creating mounts

- name: 'create mount points'
  ansible.builtin.file:
    path: "{{ item.mountpoint }}"
    state: directory
  with_flattened: "{{ filesystems }}"

- name: 'create mounts'
  ansible.posix.mount:
    path: "{{ item.mount_point }}"
    src: "LABEL={{ item.label }}"
    fstype: "{{ item.fs_type }}"
    state: mounted
  with_flattened: "{{ filesystems }}"

