---

- name: 'create data directory for mediaserver scripts'
  file:
    path: '/var/lib/mediaserver'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0775'
    state: 'directory'

- name: 'create log directory for mediaserver scripts'
  file:
    path: '/var/log/mediaserver'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0775'
    state: 'directory'

# Note this is a copy task that won't create the file if it exists...
- name: 'create log files for mediaserver scripts'
  copy:
    content: ''
    dest: '/var/log/mediaserver/{{ item }}.log'
    force: 'no'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0664'
  with_flattened: [ 'sync_music', 'sync_photos', 'normalize', 'historian_rsync' ]

# ... so we need to make sure we set ownership/permissions separately.
- name: 'set ownership/permissions on log files for mediaserver scripts'
  file:
    dest: '/var/log/mediaserver/{{ item }}.log'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0664'
  with_flattened: [ 'sync_music', 'sync_photos', 'normalize', 'historian_rsync' ]
  ignore_errors: "{{ ansible_check_mode }}"

- name: 'copy media management scripts'
  # TODO: These aren't templates...
  template:
    # Ansible should find this automatically if the file path is relative.
    # It wasn't though...
    src: '{{ role_path }}/files/{{ item }}'
    dest: '/usr/local/bin/'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_flattened: [ 'sync_music', 'sync_photos', 'normalize', 'historian_rsync' ]

- name: 'mobile photo-sync cron - lance'
  cron:
    name: 'mobile photo-sync - lance'
    minute: '0'
    hour: '*'
    user: 'plexuser'
    job: "/usr/local/bin/sync_photos -t photosync-app -s {{ mergerfs__mount_point }}/{{ media_directory }}/source_photos/lance_photosync -d {{ mergerfs__mount_point }}/{{ media_directory }}/mobile_photos_lance"

- name: 'mobile photo-sync cron - alison'
  cron:
    name: 'mobile photo-sync - alison'
    minute: '0'
    hour: '*'
    user: 'plexuser'
    job: "/usr/local/bin/sync_photos -t photosync-app -s {{ mergerfs__mount_point }}/{{ media_directory }}/source_photos/alison_photosync -d {{ mergerfs__mount_point }}/{{ media_directory }}/mobile_photos_alison"

- name: 'historian photo-sync cron'
  cron:
    name: 'historian photo-sync'
    minute: '0'
    hour: '8-23,0'
    user: 'plexuser'
    job: "/usr/local/bin/sync_photos -t historian -s {{ mergerfs__mount_point }}/{{ media_directory }}/source_photos/historian -d {{ mergerfs__mount_point }}/{{ media_directory }}/photos"

- name: 'historian rsync cron'
  cron:
    name: 'historian rsync'
    minute: '20'
    hour: '*/4'
    user: 'plexuser'
    job: "/usr/local/bin/historian_rsync -s {{ mergerfs__mount_point }}/{{ media_directory }}/historian_export -d {{ mergerfs__mount_point }}/{{ media_directory }}/source_photos/historian"

- name: 'itunes music-sync cron'
  cron:
    name: 'itunes music-sync'
    minute: '0'
    hour: '8,12,16,20'
    user: 'plexuser'
    job: "/usr/local/bin/sync_music -t itunes -s {{ mergerfs__mount_point }}/{{ media_directory }}/source_music/Lance\\'s\\ iTunes,{{ mergerfs__mount_point }}/{{ media_directory }}/source_music/Alison\\'s\\ iTunes -d {{ mergerfs__mount_point }}/{{ media_directory }}/music"

- name: 'music normalizer cron'
  cron:
    name: 'normalize'
    minute: '0'
    hour: '9,13,17,21'
    user: 'plexuser'
    job: "/usr/local/bin/normalize -s {{ mergerfs__mount_point }}/{{ media_directory }}/music -d {{ mergerfs__mount_point }}/{{ media_directory }}/music_normalized"
