---

- name: 'create data directory for mediaserver scripts'
  file:
    path: '/var/lib/mediaserver'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0775'
    state: 'directory'

- name: 'create log directory for mediaserver scripts'
  file:
    path: '/var/log/mediaserver'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0775'
    state: 'directory'

- name: 'create log files for mediaserver scripts'
  copy:
    content: ''
    dest: '/var/log/mediaserver/{{ item }}.log'
    force: 'no'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0664'
  with_flattened: [ 'sync_music', 'sync_photos', 'mediaserver', 'historian_rsync' ]

- name: 'copy media management scripts'
  # TODO: These aren't templates...
  template:
    # Ansible should find this automatically if the file path is relative.
    # It wasn't though...
    src: '{{ role_path }}/files/{{ item }}'
    dest: '/usr/local/bin/'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_flattened: [ 'sync_music', 'sync_photos', 'mediaserver', 'historian_rsync' ]

- name: 'historian rsync cron'
  cron:
    name: 'historian rsync'
    minute: '20'
    hour: '*/4'
    user: 'plexuser'
    job: "/usr/local/bin/historian_rsync -s {{ mergerfs__mount_point }}/{{ media_directory }}/historian_export -d {{ mergerfs__mount_point }}/{{ media_directory }}/source_photos/historian"

- name: 'historian photo-sync cron'
  cron:
    name: 'historian photo-sync'
    minute: '0'
    hour: '8-23,0'
    user: 'plexuser'
    job: "/usr/local/bin/mediaserver sync-photos -t historian -s {{ mergerfs__mount_point }}/{{ media_directory }}/source_photos/historian -d {{ mergerfs__mount_point }}/{{ media_directory }}/photos"

- name: 'itunes music-sync cron'
  cron:
    name: 'itunes music-sync'
    minute: '0'
    hour: '8-23,0'
    user: 'plexuser'
    job: "/usr/local/bin/mediaserver sync-music -t itunes -s {{ mergerfs__mount_point }}/{{ media_directory }}/source_music/Lance\\'s\\ iTunes,{{ mergerfs__mount_point }}/{{ media_directory }}/source_music/Alison\\'s\\ iTunes -d {{ mergerfs__mount_point }}/{{ media_directory }}/music,{{ mergerfs__mount_point }}/{{ media_directory }}/music"
