---

- name: 'create log directory for mediaserver scripts'
  file:
    path: '/var/log/mediaserver'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0775'
    state: 'directory'

- name: 'create data directory for mediaserver scripts'
  file:
    path: '/var/lib/mediaserver'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0775'
    state: 'directory'

- name: 'create log file for mediaserver script'
  copy:
    content: ''
    dest: '/var/log/mediaserver/mediaserver.log'
    force: 'no'
    group: '{{ media_group }}'
    owner: 'root'
    mode: '0664'

- name: 'copy mediaserver script'
  template:
    # Ansible should find this automatically if the file path is relative.
    # It wasn't though...
    src: '{{ role_path }}/files/{{ item }}'
    dest: '/usr/local/bin/'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_flattened: [ 'mediaserver', 'historian_rsync' ]

- name: 'itunes music-sync cron'
  cron:
    name: 'itunes music-sync'
    minute: '0'
    hour: '8-23,0'
    user: 'plexuser'
    job: "/usr/local/bin/mediaserver sync-music -s /{{ mergerfs__mount_point }}/{{ media_directory }}/source_music/Lance\\'s\\ iTunes,/{{ mergerfs__mount_point }}/{{ media_directory }}/source_music/Alison\\'s\\ iTunes -d /{{ mergerfs__mount_point }}/{{ media_directory }}/music,/{{ mergerfs__mount_point }}/{{ media_directory }}/music -t itunes"


