---

- name: 'create snapraid mount points'
  file:
      path: "{{ item.mount_point }}"
      state: directory
  loop: "{{ parity_devices + data_devices | flatten(levels=1) }}"

- debug:
    msg: "UUID={{ ansible_devices[item.device.split('/')[-1]].partitions[item.device.split('/')[-1] + '1'].uuid }}" 
  loop: "{{ parity_devices + data_devices | flatten(levels=1) }}"

- name: 'create snapraid mounts'
  mount:
      path: "{{ item.mount_point }}"
      src: "UUID={{ ansible_devices[item.device.split('/')[-1]].partitions[item.device.split('/')[-1] + '1'].uuid }}" 
      fstype: "{{ item.fs_type }}"
      state: mounted
  loop: "{{ parity_devices + data_devices | flatten(levels=1) }}"
