---

- name: 'create media group'
  group:
    name: '{{ media_group }}'
    state: 'present'

- name: 'create media users'
  user:
    name: '{{ item }}'
    append: 'yes'
    groups: '{{ media_group }}'
    shell: '/bin/bash'
  loop: "{{ media_users }}"

