---

- name: 'create media group'
  group:
    name: '{{ media_group }}'
    state: 'present'

- name: 'create media users'
  user:
    name: '{{ item.name }}'
    create_home: '{{ item.create_home }}'
    password: '{{ item.password | password_hash("sha512") }}'
    shell: '{{ item.shell }}'
    append: 'yes'
    groups: '{{ item.groups + [ media_group ] }}'
    update_password: 'on_create'
  no_log: 'true'
  with_flattened: "{{ media_users }}"

- name: 'create nopasswd sudoers'
  template:
    src: 'etc/sudoers.d/nopasswd_sudoer.j2'
    dest: '/etc/sudoers.d/10_{{ username }}'
    owner: 'root'
    group: 'root'
    mode: '0440'
  loop: '{{ nopasswd_sudoers | default([]) }}'
  loop_control:
    loop_var: username

- name: 'create plexuser'
  user:
    name: 'plexuser'
    append: 'yes'
    create_home: 'no'
    groups: '{{ media_group }}'
    password_lock: 'yes'
    shell: '/bin/bash'
  register: create_plexuser

- name: 'set plexuser uid/gid facts'
  set_fact:
    plexuser_uid: '{{ create_plexuser.uid }}'
    plexuser_gid: '{{ create_plexuser.group }}'
