---

- name: 'create media group'
  ansible.builtin.group:
    name: '{{ media_group.name }}'
    gid: '{{ media_group.gid }}'
    state: 'present'

- name: 'create media user groups'
  ansible.builtin.group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: 'present'
  loop: '{{ media_users + [plexuser] }}'

- name: 'create media users'
  ansible.builtin.user:
    name: '{{ item.name }}'
    create_home: '{{ item.create_home }}'
    password: '{{ item.password | password_hash("sha512") }}'
    shell: '{{ item.shell }}'
    append: 'yes'
    group: '{{ item.name }}'
    groups: '{{ item.groups }}'
    uid: '{{ item.uid }}'
    update_password: 'on_create'
  no_log: 'true'
  loop: '{{ media_users }}'

- name: 'create plexuser'
  ansible.builtin.user:
    name: '{{ plexuser.name }}'
    create_home: '{{ plexuser.create_home }}'
    password: '{{ plexuser.password | password_hash("sha512") }}'
    shell: '{{ plexuser.shell }}'
    append: 'yes'
    group: '{{ plexuser.name }}'
    groups: '{{ plexuser.groups }}'
    uid: '{{ plexuser.uid }}'
    update_password: 'on_create'
  no_log: 'true'
  register: created_plexuser

- name: 'set plexuser facts'
  ansible.builtin.set_fact:
    plexuser_home: '{{ created_plexuser.home }}'

- name: 'create nopasswd sudoers'
  template:
    src: 'etc/sudoers.d/nopasswd_sudoer.j2'
    dest: '/etc/sudoers.d/10_{{ username }}'
    owner: 'root'
    group: 'root'
    mode: '0440'
  loop: '{{ nopasswd_sudoers | default([]) }}'
  loop_control:
    loop_var: username
