---
# defaults file for samba

samba__base_packages:
    - 'samba'
    - 'samba-common'
    - 'samba-common-bin'

samba__services:
    - 'smbd'
    - 'nmbd'

samba__default_global:
    'workgroup'    : 'WORKGROUP'
    'server string': 'Samba Server %v'
    'server role'  : 'standalone server'
    'map to guest' : 'never'
    'dns proxy'    : 'no'
    'log file'     : '/var/log/samba/log.%m'
    'max log size' : '1000'
    'syslog'       : '0'
    'panic action' : '/usr/share/samba/panic-action %d'

samba__custom_global: {}

samba__shares: {}
