FROM ubuntu:16.04

ARG version={{ snapraid_version }}

ARG package_path
ARG package_name

#
# Build SnapRAID from source
# 

RUN apt-get update && apt-get install -y \
        checkinstall \
        curl \
        gcc \
        git \
        make \
    && curl -LO https://github.com/amadvance/snapraid/releases/download/v${version}/snapraid-${version}.tar.gz \
    && tar -xvf snapraid-${version}.tar.gz \
    && cd snapraid-${version} \
    && ./configure \
    && make -j8 \
    && make -j8 check \
    && checkinstall -Dy --install=no --nodoc \
    && mkdir -p ${package_path} \
    && mv snapraid*.deb ${package_path}/${package_name}

