FROM ubuntu:16.04
ENV VERSION={{ snapraid_version }}

#
# Build SnapRAID from source
# 

RUN apt-get update && apt-get install -y \
        checkinstall \
        curl \
        gcc \
        git \
        make \
    && curl -LO https://github.com/amadvance/snapraid/releases/download/v$VERSION/snapraid-$VERSION.tar.gz \
    && tar -xvf snapraid-$VERSION.tar.gz \
    && cd snapraid-$VERSION \
    && ./configure \
    && make -j8 \
    && make -j8 check \
    && checkinstall -Dy --install=no --nodoc \
    && mkdir /$DEBIAN_DIR \
    && cp snapraid*.deb /$DEBIAN_DIR/$DEBIAN_NAME

