---
- name: 'create snapraid build directory'
  file: dest='{{ snapraid_build_path }}' state='directory'
  when: build_snapraid.rc == 1
  listen: 'build snapraid'

- name: 'copy snapraid build script'
  template: 
    src: 'build.sh.j2' 
    dest: '{{ snapraid_build_path }}/build.sh' 
    mode: '0775'
  when: build_snapraid.rc == 1
  listen: 'build snapraid'

- name: 'copy snapraid Dockerfile'
  template: 
    src: 'Dockerfile.j2' 
    dest: '{{ snapraid_build_path }}/Dockerfile'
  when: build_snapraid.rc == 1
  listen: 'build snapraid'

- name: 'build snapraid debian package'
  command: './build.sh'
  args:
    chdir: '{{ snapraid_build_path }}'
    creates: '{{ snapraid_build_path }}/{{ snapraid_built_package_name }}'
  when: build_snapraid.rc == 1
  listen: 'build snapraid'

- name: 'install snapraid debian package'
  apt: 
    deb: '{{ snapraid_build_path }}/{{ snapraid_built_package_name }}'
  when: build_snapraid.rc == 1
  listen: 'build snapraid'


