---
# SnapRAID from source, built in a Docker container

- name: 'check snapraid install'
  shell: dpkg-query -W snapraid |grep {{ snapraid_version }}
  register: build_snapraid
  failed_when: build_snapraid.rc > 1
  changed_when: build_snapraid.rc == 1
  notify: 'build snapraid'
