---
env: 'prd'

b2_app_key_id: todo
b2_app_key: todo
restic_repo: b2:cheewee-net/{{ mediaserver_hostname }}
restic_repo_password: todo

snapraid_runner__send_email: true

mergerfs__mount_options: 'defaults,allow_other,direct_io,use_ino,category.create=eplfs,moveonenospc=true,minfreespace=20G,fsname=mergerfsPool'

